# Base Configuration
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.14.0
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
  - id: check-renovate
  - id: check-travis
  # C Configuration
- repo: https://github.com/pocc/pre-commit-hooks
  rev: master
  hooks:
  - id: clang-format
    args: [--style=Google]
  - id: clang-tidy
  - id: oclint
  - id: uncrustify
  - id: cppcheck
  - id: cpplint
  - id: include-what-you-use
