# Base Configuration
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.14.0
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
  - id: check-renovate
  - id: check-travis
  # Python Configuration
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-docstring-first
  - id: debug-statements
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
    args: [--in-place]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py3-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.7.1
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==21.9.2]
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-use-type-annotations
