name: 🐞 Bug
description: File a bug/issue
title: '[BUG] <title>'
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: What should be changed?
    description: A concise description of what should be changed.
  validations:
    required: false
- type: textarea
  attributes:
    label: Why should be changed?
    description: The reason why should be changed.
  validations:
    required: false
- type: textarea
  attributes:
    label: Which is the change?
    description: A concise description of the change.
  validations:
    required: false
